# Generated by Django 5.0.3 on 2024-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_direction', models.CharField(choices=[('AB', 'Above'), ('BE', 'Below')], default='AB', max_length=2)),
            ],
        ),
    ]
